### ISSUE TITLE
UX: Unusable for multiple (asynchronous) file encryption / decryption

### ISSUE THREAD

**Issue by vfsfitvnm** [str4d/rage#128]
Hello! I'm using the rust crate (0.4.0) in order to use age in my android application.
I'm pretty new to rust and absolutely ignorant in cryptography, so please pardon me if what I'm going to say sounds really dumb.

Use case: the user needs to access an repository of encrypted files. **I'm discarding a (hierarchy of) encrypted archives because**:
- If the user wants to access only a specific file, he's obliged to download / access the whole archive and decrypt it entirely;
- If he wants to update an archive, he also has to encrypt the whole thing and upload / store it again, instead of adding only the new file.

I couldn't figure out how to properly perform asynchronous encryption / decryption on multiple files (using the same passphrase) without making the memory usage spike: `encryptor.wrap_output(...)` takes more than 200MB of ram, so allocating a `StreamWriter<W>` for each file is unfeasible as the ram usage could (and will) spike to hundreds of megabytes (and the app will be eventually killed by the os).

On the other side, doing it synchronously, the whole thing works, but it takes a lot of time (of course), and it wouldn't be optimized as well, because both the `SecretString` and the `StreamWriter<W>` needs to be allocated / deallocated for every single file, and so there is some useless overhead.

So yeah that's all, I apologize if this makes no sense.

**Comment by str4d** [comment]
The reason for the memory usage spike is that passphrase encryption is intentionally memory-hard, to help make the passphrase difficult to brute-force. Rather than trying to use the same passphrase on every file, I'd recommend a tiered approach:

- Generate an age identity and recipient for the user.
- Encrypt the age identity using an age passphrase.

Individual files are encrypted to the user's age recipient, and the encrypted files are uploaded along with the encrypted identity. As a neat side-effect, the user doesn't need their passphrase to encrypt their files (but if you wanted this to be "required" then just don't store the age recipient, requiring the user to download and decrypt their age identity to re-derive the recipient).

To decrypt multiple files, the user first downloads and decrypts their age identity using their passphrase, and then uses that to decrypt the individual files. The memory-hard step then only happens once, no matter how many files are being decrypted. Once finished, the user can forget about the age identity, because they can always re-download and re-decrypt as long as they remember their passphrase.

**Comment by vfsfitvnm** [comment]
Thanks! Your approach seems reasonable :)
