### ISSUE TITLE
GitHub keys file contains non-recipient data

### ISSUE THREAD

**Issue by ryantm** [str4d/rage#132]
## Environment

* OS: NixOS
* rage version: 0.4.0

## What were you trying to do

Encrypt based on my GitHub keys URL.

## What happened

```
$ echo "hi" | rage -r 'https://github.com/ryantm.keys' -a
[ERROR rage] Invalid("invalid recipient key")
Error: recipients file https://github.com/ryantm.keys contains non-recipient data

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

**Comment by str4d** [comment]
Could you test this with the current latest version from the repo? I tested the above with 8368992e60cbedb2d6b725c3e25440e65d8544d1 and it worked for me.

**Comment by str4d** [comment]
I think the problem here is that `ssh-rsa` isn't supported without the `unstable` feature flag in the previous `rage` release, but when the flag isn't used, it wasn't added to the "ignored SSH key types" list. With the latest version, this shouldn't be an issue anymore (because `ssh-rsa` is now supported by default).

**Comment by ryantm** [comment]
@str4d Yes, that works for me. So, I guess this can be closed after the next release, thanks.

**Comment by str4d** [comment]
rage v0.5.0 has now been released.
