### ISSUE TITLE
Add -j flag for invoking data-less plugins

### ISSUE THREAD

**Issue by str4d** [str4d/rage#237]
Some plugins (like `yubikey-agent`, or an `sshpass` equivalent) just need the user to inform `rage` that they exist and should be used, but not to actually pass any data across. A user can currently achieve this with an "empty plugin identity", which looks like:

`AGE-PLUGIN-NAME-1SIXCHR`

where `name` is the plugin name, and `SIXCHR` is the Bech32 checksum. This has two UX flaws:

- The empty identity is a "magic string", that users need to know about in order to use these plugins.
- It needs to go into a file (since `-i` only accepts files). For a user that only uses `yubikey-agent` this would mean having a loose file around with a single magic string, the location of which they need to remember.

In a [long UX discussion](https://twitter.com/FiloSottile/status/1401578831836856325) with @FiloSottile and @benjojo, we decided to add a new `-j` flag, which does this all for the user. When `rage` sees `-j name`, it internally behaves as if it had seen a `-i file` where the file contained `AGE-PLUGIN-NAME-1SIXCHR` (with valid checksum).

This has a downstream effect on plugins: they can now distinguish a "default" behaviour. If a plugin only normally gives out plugin identities containing data, they can behave differently if they are sent (via the plugin protocol) an `add-identity` command with a known plugin name but empty data. This could be used to e.g. decrypt with a default set of identities, instead of a specific one.

`-j` is intended to be handled in-line with `-i` for deterministic decryption (#236). For simplicity, `rage` will only support a single `-j` flag, and make it incompatible with `-i` flags.

**Comment by phodina** [comment]
So is there a way to invoke the `ssh-agent`? 

I have my GPG private subkeys stored on Yubikey and I derive from them also the SSH keys.
Therefore I'm able to encrypt anything with the public key but can't decrypt the file.

**Comment by benjojo** [comment]
As far as I understand, due to the way that SSH public key encryption
works, we can't ask the agent to decrypt in the way we need it to for age.
So in your situation age files encrypted to SSH keys on yubikeys (via the
GPG/SSH menthod in particular) are not decryptable.

**Comment by phodina** [comment]
Thanks @benjojo. If I understand it correctly we would have to patch the `ssh-agent` (or `gpg-agent`) to support this functionality?

**Comment by benjojo** [comment]
Sure. But I believe there is a fundamental issue in how the GPG smartcard
works rather than how the agent protocol works

**Comment by FiloSottile** [comment]
We can't use the proper ssh-agent protocol because it only provides signing operations, not decryption, so the ability to decrypt an age ciphertext depends on where the key is actually stored:

1. if it's stored as a local SSH key file, it can be just used with `-i`
2. if it's a remote ssh-agent, we can't do much unless a custom ssh-agent extension (FiloSottile/age#7) is implemented on the remote side, which on the age side someone could write a plugin for
3. if it's actually a gpg-agent acting as an ssh-agent, it might be possible to write a plugin that talks directly to the gpg-agent, which might support the decryption operations we need, I am not sure
4. if using gpg-agent directly is not possible, and the key is a standard gpg keyring on disk, it's possible to write a plugin that uses it
5. if the key is held on an OpenPGP card like a YubiKey, it might be possible to write a plugin that uses it by talking the OpenPGP card protocol directly

(3) would be interesting, but the gpg-agent docs are a pain. See https://www.gnupg.org/documentation/manuals/gnupg/Agent-PKDECRYPT.html#Agent-PKDECRYPT and Section 6.3 of https://gnupg.org/documentation/manuals/gcrypt.pdf.

**Comment by phodina** [comment]
@FiloSottile thanks for excellent explanation and links.


> 1. if it's stored as a local SSH key file, it can be just used with `-i`
>
The simplest solution now seems to bt to use additional SSH key as a plain file.

> 2. if it's a remote ssh-agent, we can't do much unless a custom ssh-agent extension ([ssh agent support FiloSottile/age#7](https://github.com/FiloSottile/age/issues/7)) is implemented on the remote side, which on the age side someone could write a plugin for
>
As you already pointed out the ssh-agent is used for authentication. I'll have to check the issue/discussion further with the extension.

> 3. if it's actually a gpg-agent acting as an ssh-agent, it might be possible to write a plugin that talks directly to the gpg-agent, which might support the decryption operations we need, I am not sure
>
Leveraging gpg-agent acting as ssh-agent might be better way though in the end it won't work for everybody. But it's possible to interact with the gpg keyring itself though as you already mentioned unfortunately the documentation is hard to read and develop something on that at least for somebody who didn't develop gpg

> 4. if using gpg-agent directly is not possible, and the key is a standard gpg keyring on disk, it's possible to write a plugin that uses it
>
Given that there is an extension to the gpg-agent itself to act as a ssh-agent I think the previous point makes more sense as I'd rather not redo the stuff the gpg-agent does in handling and interacting with the keyring itself. Also the point is that I'd love to use age as a replacement for encrypting files with gpg and reimplementing what gpg does seems like step backwards
> 5. if the key is held on an OpenPGP card like a YubiKey, it might be possible to write a plugin that uses it by talking the OpenPGP card protocol directly
>
Not sure if this is the right move as there might be other daemons that want to talk to the card, meaning solving some arbitration through some locks and hoping the card internal state does not change, and also the documentation on this topic is kinda hard to swallow

**Comment by IxDay** [comment]
Sorry to re-open this thread but I want to be sure I properly understand it. 
Currently there is no way to use `rage` if `yubikey-agent` is running, right? I am following a bunch of issues here and there and a lot of stuff seems to be in progress.
As far as I get it someone need to implement a `ssh agent` plugin to handle the decryption right? Because only one process can keep a hold on the Yubikey, right? 
If I am wrong, can someone tell me which ID I need to pass to `rage -j ...` in order for this to work? I am looking everywhere and there is no mention of this Bech32 in `yubikey-agent` binary.
