### ISSUE TITLE
Detect and report unsupported SSH key types

### ISSUE THREAD

**Issue by Firstyear** [str4d/rage#272]
## Environment

* OS: Macos 11.6.1
* rage version: 0.7.0

## What were you trying to do

After checking the --help, I noticed the ability to use ssh identities. I tried with both an sk-ecdsa key and an ecdsa and in both cases I saw:

```
Error: Invalid recipient '/Users/william/.ssh/id_ecdsa_yn5ca.pub'

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report

Error: recipients file /Users/william/.ssh/id_ecdsa_old.pub contains non-recipient data on line 1

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

I think from having a quick look at the source in https://github.com/str4d/rage/blob/main/age/src/ssh/identity.rs that only ed25519 and rsa are supported. 

So I would like to report this bug as:

* When an ssh public key file of a valid format is passed to rage, but of an unsupported key type, rage should inform the user that the key type isn't supported rather than the generic message above
* That rage should support sk-ecdsa / sk-ed25519 (aka yubikey backed keys)
* And that rage should support ecdsa cryptography

Thank you! So far rage has been awesome, and I hope this report helps you :)

**Comment by str4d** [comment]
Both age and rage only support a subset of SSH key types

**Comment by str4d** [comment]
Both age and rage only support a subset of SSH key types for backwards compatibility. The CLI apps are unlikely to support every possible variant of SSH key, because each one needs individual custom support for a compatible encryption protocol. IIRC `ssh-rsa` was selected as the most commonly-observed, while `ssh-ed25519` was close to what age native identities use, and could share the cryptography logic. Other SSH key types can be supported via age plugins, though this would not enable simply encrypting to an SSH pubkey (you'd need to perform a straightforward transformation of it into an age plugin recipient format, so the clients know which plugin to route to).

I'll also note here that it is impossible to support `sk-*` SSH keys. These use the FIDO2 protocol, which only supports authentication; it doesn't expose the necessary primitive to also implement asymmetric encryption.

If you want YubiKey-backed keys, you can use the [`age-plugin-yubikey` plugin](https://github.com/str4d/age-plugin-yubikey) which is currently in beta. It uses the PIV applet, and won't collide with FIDO2 SSH keys, so you can use them together for a single signing-and-decryption token of you wish.

The suggestion to detect unsupported SSH key types is a good one. I do have some logic for this already, to give errors about unsupported encrypted SSH key formats, so I'll extend it to key types as well.

**Comment by Firstyear** [comment]
No problem! Thanks for explaining this. I think in this case the error saying the keys are unsupported would resole my issue as a whole :) 

Thank you!

**Comment by yakimant** [comment]
I wonder, why `-sk` keys are supported also for git signing, so not only authentication.

**Comment by str4d** [comment]
Authentication and Git signing both use the same primitive: a signature.

**Comment by Firstyear** [comment]
The key point here is that -sk keys can't do encryption or key derivation per the CTAP specification.

**Comment by yakimant** [comment]
Thanks, I though you can do any kind of thing if you have a private/public keys pair, but I'm far from understanging.

BTW, I found this repo in the awesome-age list:
https://github.com/olastor/age-plugin-fido2-hmac
