### ISSUE TITLE
Deterministic output

### ISSUE THREAD

**Issue by ThinkChaos** [str4d/rage#355]
I'm trying to use rage in a reproducible way, but the output varies between runs  for the same key and plaintext.
The key I tried with is an ssh-ed25519 public key and I'm using `--armor`.

The use case is building system configurations with NixOS that contain encrypted secrets, decrypted on demand by the target system. It works, but since the rage output is non deterministic, secrets are seen as changed by Nix on every build causing unnecessary churn.

I was wondering if there's a way rage could be deterministic. Maybe take a RNG seed as CLI argument?
I tried patching out the randomness of the nonce and just using zeros but the output still varies.
Is this doable? Would there be security implications besides being able to tell 2 messages have the same content?

The alternative for me would be to generate the cipher text outside of Nix, and storing that in a way Nix can import. That way Nix would always see the same cipher text and the build would be reproducible.
But I'd prefer not having a separate step required to build/deploy system configs.

Thanks for the great tool!

**Comment by str4d** [comment]
Deterministic ciphertexts are out-of-scope for this tool, as they are non-compliant with the [age specification](https://c2sp.org/age#payload):
> The binary payload [...] begins with a 16-byte nonce generated by the sender from a CSPRNG. A new nonce **MUST** be generated for each file.
>
> [...]
>
> The payload **MUST NOT** be modified without re-encrypting it as a new file with a fresh nonce.

Individual recipient stanzas also introduce non-determinism, which helps to mitigate certain attacks. The age specification similarly has a **MUST** requirement on using randomness for the `x25519` and `scrypt` recipient stanzas.

Introducing a way to fix the sampled randomness (thus causing the key and nonce to be fixed) would introduce a significant security vulnerability, because `(key, nonce)` reuse in ChaCha20Poly1305 causes catastrophic loss of privacy. If a user unwittingly used the same fixed randomness for two or more different files, they'd lose privacy for all of them. This is a footgun I am completely unwilling to include in `rage`.

---

The above being said, once you have an encrypted age file, you can reuse it as long as the encrypted message isn't being changed (at which point per above it needs to be re-encrypted). So it may be possible to write some wrapping Nix logic (maybe, I've never used NixOS) that checks whether the current secret matches the encrypted secret, and re-uses the existing encrypted file if so (thus treating it as not changed).
