### ISSUE TITLE
[decryption] unable to use an identity provided via stdin

### ISSUE THREAD

**Issue by motiejus** [str4d/rage#379]
## Environment

* OS: NixOS 22.11
* rage version: 0.9.0 (from nixpkgs-22.11)

## What were you trying to do

Use an identity that was generated on the fly from an ssh private key:

```
$ rage -d -i <(sudo ssh-to-age -private-key -i /etc/ssh/ssh_host_ed25519_key)  secret.age 
Error: Missing identities.
Did you forget to specify -i/--identity?
```

## Expected behavior

Seems to work with `age`:

```
$ aage -d -i <(sudo ssh-to-age -private-key -i /etc/ssh/ssh_host_ed25519_key)  secret.age 
<plaintext>
```

**Comment by str4d** [comment]
The issue here is that because `-i` currently only supports on-disk files with filenames (because #177 has not yet been implemented), we assume that we can read from the identity file more than once. This assumption is broken by named pipes (as well as stdin). #354 was one approach to fixing this; I plan on taking the approach I outlined in https://github.com/str4d/rage/pull/354#issuecomment-1587732589.
