### ISSUE TITLE
Grease data included in file header

### ISSUE THREAD

**Issue by olastor** [str4d/rage#413]
## Environment

* OS: Linux
* rage version: 0.9.2

## What were you trying to do

Creating a plugin

## What happened

After successfull test encryption via the plugin, the file header (in the encrypted file) not only included the keys wrapped with my plugin, but also some random grease data. I am not sure if I understand the [spec](https://github.com/C2SP/C2SP/blob/main/age-plugin.md#grease) here correctly. Is this intended to happen? I don't see why adding that to the header would bring any benefit. It seems to increase the file size unnecessarily.

```
-> my-plugin [...]
[...]
-> my-plugin [...]
[...]
-> @r9C{x-grease k#qL>i 2bU A;2E1 c~K8{S
2xeT0hKe3O8p8r+KvoMTHGxtT/TU6rYiJf6zaAdeLworBC/H7GYVWgwKjGBGKWSx
1DNhTkIih+iQQ3uctoAmIVqPBSQFEo8crEtJeiC9pOEE6G05x6vyYXW0CBqBetw4

--- [...]

[...]
```

**Comment by str4d** [comment]
Yes this is intentional. `rage` adds it randomly with low probability, with the intention of ensuring that age's one joint remains functional (that is, ensuring that age file parsers always handle stanza parsing correctly, instead of taking shortcuts based on the "expected" stanzas). See also my comments in https://github.com/str4d/rage/pull/365#issuecomment-1412169307.

The spec you referenced is the `age-plugin` protocol, which is separately greased. It shares the stanza format, but is otherwise independent (grease in that protocol doesn't become part of a file, and vice versa).
