### ISSUE TITLE
v0.9 Breaking Change?

### ISSUE THREAD

**Issue by greg-hellings** [str4d/rage#421]
## Environment

* OS: NixOS
* rage version: v0.9.0 and later

## What were you trying to do

Read files encrypted with a version of rage < 0.9.0

## What happened

The file is read-able with versions of rage up through 0.8.1, but versions after 0.9.0 fail to read the file. In this case the file was originally created with version 0.7.2 of rage through the agenix tool.

```
greg@jude ~/tmp main @ rage -V
rage 0.8.1
greg@jude ~/tmp main @ rage --decrypt -i ~/.ssh/id_rsa -o - /etc/nixos/secrets/linode-forgejo-runner.age
TOKEN=<redacted>
greg@jude ~/tmp main @ rage -V
rage 0.9.0
greg@jude ~/tmp main @ rage --decrypt -i ~/.ssh/id_rsa -o - /etc/nixos/secrets/linode-forgejo-runner.age
Error: Decryption failed
```

The same behavior is witnessed with v0.9.2.

**Comment by greg-hellings** [comment]
Further info - trying to recreate the file anew with rage v0.9.2 on my system gives me the following head-scratching message:

```
greg@jude /e/n/secrets main @ agenix -e linode-forgejo-runner.age
cp: cannot stat '/tmp/tmp.mpGU2kPBvs/linode-forgejo-runner.age': No such file or directory
Error: Unsupported SSH key: ⁨⁩

Unsupported SSH Key Type
------------------------
OpenSSH supports various different key types, but rage only supports a
subset of these for backwards compatibility, specifically the 'ssh-rsa'
and 'ssh-ed25519' key types. This SSH key uses the unsupported key type
'⁨ssh-rsa⁩'.
```

The underlying call is simply to `rage --recipient <key> --recipient <key> ...  -o /tmp/tmp.pEF9ypHa77/linode-forgejo-runner.age`, all of which seems pretty straightforward yet generates the message about `ssh-rsa` being supported, but apparently not.

If this is an issue with the NixOS packaging, then I'm happy to take information back to the packagers to see how this might be fixed.

**Comment by str4d** [comment]
It looks like this was caused by #349, in which the `rsa` crate was upgraded from 0.6 to 0.7. [`rsa 0.7.0`](https://github.com/RustCrypto/RSA/blob/master/CHANGELOG.md#070-2022-10-10-yanked) set a default maximum RSA public key size of 4096 bits, and your encryption command includes 8192-bit keys.

Now, it was "fine" to make this change in 0.9 because that was a breaking change release (as are all 0.Y releases under Rust SemVer). However, this should have been documented in the 0.9.0 changelog; I will do so. I will also consider adding a flag for overriding the maximum RSA key size (as `rage` _should_ have a maximum bound, for [the same reason that a maximum was added to the `rsa` crate](https://github.com/RustCrypto/RSA/issues/166)), though this may take a bit longer to implement.

**Comment by str4d** [comment]
Hmm, looking further at the `rsa` crate, I _think_ that the breaking change was only for using `ssh-rsa` public keys larger than 4096 bits in `--recipient`. AFAICT private keys don't have that same restriction, so encrypting to a large-modulus identity file with `--identity` should still work in 0.9.

**Comment by greg-hellings** [comment]
Ah, the key size strikes again. I thought I had squashed all of my 8192 keys. This caused me to finish my upgrade to all ED25519 keys and re-encrypt the files. So there is no immediate issue for me. Likely a comment in the release notes is good enough.

**Comment by str4d** [comment]
I've updated the changelog in #425 as well as adding a new error to handle this case.
